[Ingester]
Horizon = 4               # this is the minimum latency in fragments [number of fragments]
ControllerFrequency = 2   # how often the fragment samples are sent [number of fragments]
HeapSize = 60             # minimum fragments to keep in memory [number of fragments]

Pipe = "/dev/shm/repr_1280x720"

[Representations.sd]
Pipe = "/dev/shm/repr_1024x576"

[Representations.lq]
Pipe = "/dev/shm/repr_480x270"

[Server]
Address = "0.0.0.0:8080"
