[Ingester]
FragmentDuration = 1000   # from muxer `-frag_duration` [milliseconds]
Horizon = 6               # minimum latency in fragments [number of fragments]
ControllerFrequency = 2   # fragment samples sending frequency [number of fragments]
HeapSize = 120            # minimum fragments to keep in heap [number of fragments]

[Representations.d]
Pipe = "/dev/shm/repr_1920x1080"
Log = true

[Representations.c]
Pipe = "/dev/shm/repr_1280x720"
Log = true

[Representations.b]
Pipe = "/dev/shm/repr_1024x576"

[Representations.a]
Pipe = "/dev/shm/repr_480x270"

[Server]
Address = "0.0.0.0:8080"
Root = "/mux"
