[Ingester]
SegmentDuration = 5000
Horizon = 3

[Representations.lq]
Pipe = "/dev/shm/repr_480x270"

[Representations.sd]
Pipe = "/dev/shm/repr_1024x576"

[Representations.hd]
Pipe = "/dev/shm/repr_1280x720"

[Representations.fhd]
Pipe = "/dev/shm/repr_1920x1080"

[Server]
Address = "localhost:8080"