[Ingester]
SegmentDuration = 4000
Horizon = 3

[Representations.fhd]
Pipe = "/dev/shm/repr_1920x1080"

[Representations.hd]
Pipe = "/dev/shm/repr_1280x720"

[Representations.sd]
Pipe = "/dev/shm/repr_1024x576"

[Representations.lq]
Pipe = "/dev/shm/repr_480x270"

[Server]
Address = "0.0.0.0:8080"
